# Autogenerated wrapper script for gfxinfo_c_bindings_jll for i686-linux-gnu
export libgfxinfo_c_bindings

using libdrm_jll
JLLWrappers.@generate_wrapper_header("gfxinfo_c_bindings")
JLLWrappers.@declare_library_product(libgfxinfo_c_bindings, "libgfxinfo_c_bindings.so")
function __init__()
    JLLWrappers.@generate_init_header(libdrm_jll)
    JLLWrappers.@init_library_product(
        libgfxinfo_c_bindings,
        "lib/libgfxinfo_c_bindings.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
