# Autogenerated wrapper script for gfxinfo_c_bindings_jll for x86_64-w64-mingw32
export libgfxinfo_c_bindings

using libdrm_jll
JLLWrappers.@generate_wrapper_header("gfxinfo_c_bindings")
JLLWrappers.@declare_library_product(libgfxinfo_c_bindings, "gfxinfo_c_bindings.dll")
function __init__()
    JLLWrappers.@generate_init_header(libdrm_jll)
    JLLWrappers.@init_library_product(
        libgfxinfo_c_bindings,
        "bin\\gfxinfo_c_bindings.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
